### ISSUE TITLE
Duplicate namespace for assertion.AttributeType

### ISSUE THREAD

**Issue by thanray** [Currence-Online/iDIN-libraries-java#6] opened 2019-10-14 08:11 UTC
Test for sign-request: AutenticationRequest with details of documentId gives error because of two of AttributeType has same namespace (assertion,protocol) 

```
   @Test
    public void testCreateDocumentIdAttribute() throws IOException, DatatypeConfigurationException, ParserConfigurationException, SAXException, CommunicatorException,
            JAXBException, TransformerException {
        //
        final AuthenticationRequest transactionReq = new AuthenticationRequest();
        final Configuration config = getConfig();

        transactionReq.setMerchantReference("merchantRef");
        transactionReq.setDocumentID("docId");
        transactionReq.setRequestedServiceID(new ServiceId("reqServiceId"));

        // Act
        Element transaction = instance.getTransaction(config, transactionReq);

        String xml = new iDxMessageBuilder().getTransactionRequest(config, transactionReq, transaction);

        // Assert
        assertNotNull(transaction);
        assertNotNull(xml);
        assertTrue(xml.contains("Attribute "));
    }



`com.sun.xml.internal.bind.v2.runtime.IllegalAnnotationsException: 1 counts of IllegalAnnotationExceptions

Two classes have the same XML type name "{urn:oasis:names:tc:SAML:2.0:assertion}AttributeType". Use @XmlType.name and @XmlType.namespace to assign different names to them.
	this problem is related to the following location:
		at schemas.saml.protocol.AttributeType
		at public javax.xml.bind.JAXBElement schemas.saml.protocol.ObjectFactory.createAttribute(schemas.saml.protocol.AttributeType)
		at schemas.saml.protocol.ObjectFactory
		at protected java.util.List schemas.saml.protocol.SubjectType.content
		at schemas.saml.protocol.SubjectType
		at protected schemas.saml.protocol.SubjectType schemas.saml.protocol.AuthnRequestType.subject
		at schemas.saml.protocol.AuthnRequestType
	this problem is related to the following location:
		at schemas.saml.assertion.AttributeType
		at @javax.xml.bind.annotation.XmlSeeAlso(value=[class schemas.saml.assertion.AttributeType])
		at protected schemas.saml.protocol.ExtensionsType schemas.saml.protocol.StatusResponseType.extensions
		at schemas.saml.protocol.StatusResponseType
		at schemas.saml.protocol.ResponseType
		at public schemas.saml.protocol.ResponseType schemas.saml.protocol.ObjectFactory.createResponseType()
		at schemas.saml.protocol.ObjectFactory
		at protected java.util.List schemas.saml.protocol.SubjectType.content
		at schemas.saml.protocol.SubjectType
		at protected schemas.saml.protocol.SubjectType schemas.saml.protocol.AuthnRequestType.subject
		at schemas.saml.protocol.AuthnRequestType
`
```

**Comment by grigoresc** [comment] 2020-05-21 09:15
We have tried and could not reproduce the issue on our side. Is the issue still present?

We would like to know more details about the context of the issue.

- What maven version are you using?
- What java version, vendor and OS are you using?
- Are there any changes made in the source code pf the merchant library that may lead to this error?
- Are you using a specific JAXB (JSR-222) implementation instead of the Java SE implementation? 


Thanks.

**Comment by grigoresc** [comment] 2021-01-21 06:23
We'll close this since we don't have any additional info.

**Closed as completed by grigoresc** 2021-01-21 06:23 UTC
Labels: question, wontfix
